#!/bin/bash
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

dir="$(dirname $0)"

. "$dir"/info

for file in "$dir"/include-*; do
  name="$(echo $file | sed -e 's,^.*/include-,,')"
  hooks+=($name)
  . "$file"
done

if [ "$RELEASE" == "$(uname -r)" ]; then
  for hook in ${hooks[@]}; do
    add_$hook
  done
else
  yesno "Does the bug you are reporting affect this computer? " yep
  same_system=$REPLY
  for hook in ${hooks[@]}; do
    ask_$hook
  done
fi
