name: Build

on:
  push:
  pull_request:

jobs:

  bash:
    strategy:
      matrix:
        image: [
            "debian:bookworm",
            "debian:trixie",
            "debian:sid",
            "ubuntu:jammy",
            "ubuntu:noble",
            "ubuntu:oracular",
            "ubuntu:plucky"
        ]

    name: Build Source Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Import GPG Key
        env:
            KEY_FILE: ${{ secrets.KEY_FILE }}
        run: |
          echo "$KEY_FILE" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Set Default GPG Key
        env:
            KEY_ID: ${{ secrets.KEY_ID }}
        run: echo "default-key = $KEY_ID" >> ~/.gnupg/gpg.conf
      - name: Run Bootstrap
        run: |
          scripts/debian/docker_bootstrap-image.sh \
            amd64 $(echo ${{ matrix.image }} | tr ':' ' ')
