name: Shell Script Lint

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          find . -type f -name "*.sh" -print0 |\
          xargs -0 shellcheck -S error
