name: Lint

on:
  push:
  pull_request:

jobs:

  bash:
    name: Lint Bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" -print0 |\
          xargs -0 shellcheck -S error

  ruff:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run ruff
        run: ruff check --output-format=github

      - name: Run black
        run: black --check --diff .
